# №1

In [117]:
import numpy as np

A = np.array([[10, 1, -1], [1, 10, -1], [-1, 1, 10]])
b = np.array([11, 10, 10])
np.linalg.solve(A, b) # ответ через встроенную функцию

array([1.1020202 , 0.99090909, 1.01111111])

In [118]:
def solve(A, b, eps=1e-6):
    B = np.zeros(A.shape)
    q = np.zeros(b.shape)

    for i in range(A.shape[0]):
        B[i] = A[i]/A[i][i]
        q[i] = b[i]/A[i][i]
        B[i][i] = 0
        
    xl = np.ones(q.shape)
    xk = np.zeros(q.shape)
    
    while np.linalg.norm(xk-xl) >= eps:
        xl = xk.copy()
        xk = B.dot(xl) + q
    
    return xk, B, q
xk, B, q = solve(A, b)
xk, B, q

(array([1.1020202, 1.0111111, 0.9909091]), array([[ 0. ,  0.1, -0.1],
        [ 0.1,  0. , -0.1],
        [-0.1,  0.1,  0. ]]), array([1.1, 1. , 1. ]))

 # №2
 ### Дана последовательность $x_k = Bx_{k-1} \ (*) $ 
 a) При каких условиях последовательность сходится?
 
 Рассмотрим уравнения $\hat x_=B\hat x$ и $x_k = Bx_{k-1}$. Далее $\lVert \hat x - x_k \lVert = \lVert B(\hat x - x_{k-1}) \lVert \leq \lVert B^k \lVert \lVert \hat x - x_0 \lVert$, откуда сходимость будет следовать при норме матрицы $B$ меньше 1.
 
 б) Привести пример матрицы $B$, когда  все компоненты предела $x_k$ равны.
 
 Рассмотрим уравнение $$\hat x=B\hat x$$. Далее, можно непосредственным перемножением получить уравнение для каждой из компонент в виде $\hat x^{(i)} = \sum_{j=0}^{n}B_{ij}*\hat x^{(j)}$. Поскольку все компоненты равны, то можно переписать это в виде: $\hat x = (\sum_{j=0}^{n}B_{ij})* \hat x$, из чего следует, что $\sum_{j=0}^{n}B_{ij} = 1$, либо решение тривиально. Рассмотрим матричную норму $\lVert B \lVert_\inf = \max_{i=0..n} \sum_{j=0}^{n} |b_{ij}|$. По свойствам модуля сумма модулей больше модуля суммы, что значит сумма $\sum_{j=0}^{n}|B_{ij}| \geq 1$, что влечет за собой $\lVert B \lVert_\inf \geq 1$. По свойству эквивалентности норм в конечномерных пространствах данное неравенство будет верным для всех норм, а значит нет такой матрицы, для которой итерационная последовательность будет сходиться при данных условиях. Значит, есть только тривиальное решение x, для которого подойдет любая матрица B c нормой  $ < 1$.

In [110]:
B = np.array([[0, 0.25, 0.25], [0.25, 0, 0.25], [0.25, 0.25, 0]])
B

array([[0.  , 0.25, 0.25],
       [0.25, 0.  , 0.25],
       [0.25, 0.25, 0.  ]])

In [111]:
np.linalg.norm(B)

0.6123724356957945

In [112]:
xl = np.array([0, 1, 3])
xk = np.array([0, 1, 2])

while np.linalg.norm(xk-xl) >= 1e-12:
    xl = xk.copy()
    xk = B.dot(xl)
xk

array([4.54747351e-13, 4.54747351e-13, 4.54747351e-13])

# №3



In [135]:
from concurrent.futures import ThreadPoolExecutor

def dot(vec1, vec2):
    return sum(map(lambda x: x[0]*x[1], zip(vec1, vec2)))

def matrix_vector_mult(matrix, vector):
    assert len(matrix[0]) == len(vector)
    executor = ThreadPoolExecutor()
    result = executor.map(lambda v: dot(v, vector), matrix)
    return list(result)

matrix = [[np.random.randint(100) for i in range(10)] for i in range(16)]
vector = [np.random.randint(100) for i in range(10)]

matrix_vector_mult(matrix, vector)

[28156,
 27815,
 19658,
 33948,
 30986,
 21332,
 25541,
 29198,
 16433,
 29542,
 19460,
 14891,
 24120,
 28558,
 23552,
 21347]

In [136]:
np.dot(matrix, vector) # проверка

array([28156, 27815, 19658, 33948, 30986, 21332, 25541, 29198, 16433,
       29542, 19460, 14891, 24120, 28558, 23552, 21347])